### ISSUE TITLE
Unable to use the vargs library

### ISSUE THREAD

**Issue by vbrazo** [nedpals/v-args#2]
After running `v install nedpals.args`, I got `vargs` installed locally, however I'm unable to use the library. Here is a piece of feedback from my terminal:

![Screen_Shot_2019-09-14_at_4 01 50_AM](https://user-images.githubusercontent.com/1292556/64907329-b4a26400-d6a5-11e9-91a2-05bce36b7399.png)

I think the issue is happening because after downloading the library, the folder name is wrong. It's missing the `v` in `vargs`: `/Users/voliveira/.vmodules/nedpals/args/`.

**Comment by tomByrer** [comment]
What version do you have installed?

Since the package was [renamed to `vargs`](https://github.com/nedpals/vargs#breaking-changes-in-03), perhaps vpn didn't catch up yet?

**Comment by vbrazo** [comment]
I think it was the latest `v` and latest `vargs`.

**Comment by nedpals** [comment]
Hi @vbrazo! Sorry for that issue. Since vpm.best doesn't support renaming modules right now, I have no choice but to resubmit the module with an updated name. Try installing it again with `v install nedpals.vargs` :D 

I'll update the README to reflect the changes 👍
